// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordatorioContraseñas.Modelos;

namespace RecordatorioContraseñas.Migrations
{
    [DbContext(typeof(RecordatorioContrasenaContext))]
    partial class RecordatorioContrasenaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecordatorioContraseñas.Modelos.Cuentas", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnName("contrasena")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnName("fechaModificacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnName("usuario")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<byte>("UsuarioId")
                        .HasColumnName("usuario_id")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cuentas");
                });

            modelBuilder.Entity("RecordatorioContraseñas.Modelos.Usuarios", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Activo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("activo")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("('1')");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnName("contrasena")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnName("fechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnName("usuario")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Usuario")
                        .IsUnique()
                        .HasName("UQ__usuarios__9AFF8FC625D0757F");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("RecordatorioContraseñas.Modelos.Cuentas", b =>
                {
                    b.HasOne("RecordatorioContraseñas.Modelos.Usuarios", "UsuarioNavigation")
                        .WithMany("Cuentas")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__cuentaa__usuario__4D94879B")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
